// <auto-generated />
using HurManager.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HurManager.Dal.Migrations
{
    [DbContext(typeof(HurManagerContext))]
    partial class HurManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HurManager.Domain.Entities.Business.HouseEntity", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HouseId");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("[Address] IS NOT NULL");

                    b.ToTable("House");

                    b.HasData(
                        new
                        {
                            HouseId = 1,
                            Address = "2094 Arrowood Drive"
                        },
                        new
                        {
                            HouseId = 2,
                            Address = "421 Oakwood Avenue"
                        },
                        new
                        {
                            HouseId = 3,
                            Address = "4927 Stoneybrook Road"
                        },
                        new
                        {
                            HouseId = 4,
                            Address = "2144 College View"
                        },
                        new
                        {
                            HouseId = 5,
                            Address = "2568 Stone Lane"
                        },
                        new
                        {
                            HouseId = 6,
                            Address = "3465 Worley Avenue"
                        },
                        new
                        {
                            HouseId = 7,
                            Address = "5003 Hidden Valley Road"
                        },
                        new
                        {
                            HouseId = 8,
                            Address = "2022 Karen Lane"
                        },
                        new
                        {
                            HouseId = 9,
                            Address = "2905 Crestview Terrace"
                        },
                        new
                        {
                            HouseId = 10,
                            Address = "567 Upton Avenue"
                        });
                });

            modelBuilder.Entity("HurManager.Domain.Entities.Business.WaterMeterEntity", b =>
                {
                    b.Property<int>("WaterMeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FactoryNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("Reading")
                        .HasColumnType("int");

                    b.HasKey("WaterMeterId");

                    b.HasIndex("FactoryNumber")
                        .IsUnique()
                        .HasFilter("[FactoryNumber] IS NOT NULL");

                    b.HasIndex("HouseId")
                        .IsUnique();

                    b.ToTable("WaterMeter");

                    b.HasData(
                        new
                        {
                            WaterMeterId = 1,
                            FactoryNumber = "A701959",
                            HouseId = 1,
                            Reading = 2649
                        },
                        new
                        {
                            WaterMeterId = 2,
                            FactoryNumber = "B176459",
                            HouseId = 2,
                            Reading = 6754
                        },
                        new
                        {
                            WaterMeterId = 3,
                            FactoryNumber = "C057998",
                            HouseId = 3,
                            Reading = 4582
                        },
                        new
                        {
                            WaterMeterId = 4,
                            FactoryNumber = "A297539",
                            HouseId = 4,
                            Reading = 4868
                        },
                        new
                        {
                            WaterMeterId = 5,
                            FactoryNumber = "N934471",
                            HouseId = 5,
                            Reading = 8796
                        },
                        new
                        {
                            WaterMeterId = 6,
                            FactoryNumber = "Z435565",
                            HouseId = 6,
                            Reading = 2910
                        },
                        new
                        {
                            WaterMeterId = 7,
                            FactoryNumber = "A199350",
                            HouseId = 7,
                            Reading = 3338
                        },
                        new
                        {
                            WaterMeterId = 8,
                            FactoryNumber = "Z347827",
                            HouseId = 8,
                            Reading = 3183
                        },
                        new
                        {
                            WaterMeterId = 9,
                            FactoryNumber = "Q481678",
                            HouseId = 9,
                            Reading = 5930
                        });
                });

            modelBuilder.Entity("HurManager.Domain.Entities.Business.WaterMeterEntity", b =>
                {
                    b.HasOne("HurManager.Domain.Entities.Business.HouseEntity", "House")
                        .WithOne("WaterMeter")
                        .HasForeignKey("HurManager.Domain.Entities.Business.WaterMeterEntity", "HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("HurManager.Domain.Entities.Business.HouseEntity", b =>
                {
                    b.Navigation("WaterMeter");
                });
#pragma warning restore 612, 618
        }
    }
}
